import Link from "next/link";
import { activityLogs, adminFiles, adminUsers, growthData, overviewStats, storageData, systemServices } from "@/lib/admin/adminMockData";
import { Badge, formatBytes, MiniBarChart, PageHeader, Section, StatCard, StorageProgressBar, UserCell } from "@/components/admin/admin-ui";
import AdminIcon from "@/components/admin/admin-icons";

const monthLabels = ["Jul", "", "", "Oct", "", "", "Jan", "", "", "Apr", "", "Jun"];

export default function OverviewPage() {
  const usedPercent = Math.round((overviewStats.storageUsed / overviewStats.storageQuota) * 100);
  return <><PageHeader eyebrow="Admin overview" title="Platform at a glance" description="Monitor account growth, storage consumption, uploads, and service health across Storix." actions={<button type="button" className="flex h-9 items-center gap-2 rounded-md border border-gray-200 bg-white px-3 text-xs font-semibold text-gray-700 shadow-sm"><AdminIcon name="refresh" className="h-3.5 w-3.5" />Refresh data</button>} />
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4 xl:grid-cols-6"><StatCard label="Total users" value={overviewStats.totalUsers.toLocaleString()} detail="+7.4% this month" icon="users" /><StatCard label="Active users" value={overviewStats.activeUsers.toLocaleString()} detail="88.8% of accounts" tone="green" icon="activity" /><StatCard label="New this month" value={overviewStats.newUsers} detail="42 joined this week" tone="violet" icon="users" /><StatCard label="Total files" value="48.2K" detail="1,248 recent uploads" tone="amber" icon="files" /><StatCard label="Storage used" value={formatBytes(overviewStats.storageUsed)} detail={`${usedPercent}% of assigned quota`} icon="storage" /><StatCard label="Failed uploads" value={overviewStats.failedUploads} detail="1.1% failure rate" tone="red" icon="alert" /></div>
    <div className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><Section title="User growth" description="New and active accounts over the last 12 months" action={<Badge tone="green">+18.2% yearly</Badge>}><MiniBarChart values={growthData} labels={monthLabels} /></Section><Section title="Storage usage" description="Platform-wide assigned quota"><div className="flex items-end justify-between"><div><p className="text-3xl font-semibold text-gray-950">18.6 TB</p><p className="mt-1 text-xs text-gray-500">of 32 TB assigned</p></div><span className="text-sm font-semibold text-blue-600">{usedPercent}%</span></div><div className="mt-6"><StorageProgressBar used={overviewStats.storageUsed} limit={overviewStats.storageQuota} showLabel={false} /></div><div className="mt-5 grid grid-cols-3 gap-2 border-t border-gray-100 pt-4 text-center"><div><p className="text-sm font-semibold">7.7 GB</p><p className="text-[10px] text-gray-500">Avg. per user</p></div><div><p className="text-sm font-semibold">13.4 TB</p><p className="text-[10px] text-gray-500">Available</p></div><div><p className="text-sm font-semibold">38%</p><p className="text-[10px] text-gray-500">Video files</p></div></div></Section></div>
    <div className="grid gap-4 xl:grid-cols-2"><Section title="Storage growth" description="Monthly utilization trend"><MiniBarChart values={storageData} color="bg-emerald-600" labels={monthLabels} /></Section><Section title="Top users by storage" description="Accounts with the highest current usage" action={<Link href="/admin/storage" className="text-xs font-semibold text-blue-600">View analytics</Link>}><div className="space-y-4">{[...adminUsers].sort((a,b) => b.storageUsed - a.storageUsed).slice(0,5).map((user) => <div key={user.id} className="grid grid-cols-[minmax(0,1fr)_minmax(110px,180px)] items-center gap-4"><UserCell user={user} /><StorageProgressBar used={user.storageUsed} limit={user.storageLimit} /></div>)}</div></Section></div>
    <div className="grid gap-4 xl:grid-cols-[1fr_1fr_.7fr]"><Section title="Recent activity" action={<Link href="/admin/activity" className="text-xs font-semibold text-blue-600">View logs</Link>}><div className="divide-y divide-gray-100">{activityLogs.slice(0,4).map((item) => <div key={item.id} className="flex gap-3 py-3 first:pt-0 last:pb-0"><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${item.status === "failed" ? "bg-red-500" : item.status === "warning" ? "bg-amber-500" : "bg-emerald-500"}`} /><div className="min-w-0"><p className="text-xs font-semibold text-gray-800">{item.action} <span className="font-normal text-gray-500">by {item.user}</span></p><p className="mt-1 truncate text-[11px] text-gray-400">{item.details}</p></div></div>)}</div></Section><Section title="Recent uploads" action={<Link href="/admin/files" className="text-xs font-semibold text-blue-600">All files</Link>}><div className="divide-y divide-gray-100">{adminFiles.slice(0,4).map((file) => <div key={file.id} className="flex items-center justify-between gap-3 py-3 first:pt-0 last:pb-0"><div className="min-w-0"><p className="truncate text-xs font-semibold text-gray-800">{file.name}</p><p className="mt-1 text-[11px] text-gray-400">{file.owner} / {formatBytes(file.size)}</p></div><Badge tone={file.status === "ready" ? "green" : file.status === "failed" ? "red" : "amber"}>{file.status}</Badge></div>)}</div></Section><Section title="System status"><div className="space-y-3">{systemServices.slice(0,5).map((service) => <div key={service.name} className="flex items-center justify-between gap-2"><span className="text-xs text-gray-600">{service.name}</span><span className={`h-2 w-2 rounded-full ${service.status === "operational" ? "bg-emerald-500" : "bg-amber-500"}`} title={service.status} /></div>)}</div><Link href="/admin/health" className="mt-5 flex items-center gap-1 text-xs font-semibold text-blue-600">System health <AdminIcon name="arrow" className="h-3 w-3" /></Link></Section></div>
  </>;
}
