"use client";

import { useState } from "react";
import { adminSettings } from "@/lib/admin/adminMockData";
import { PageHeader, Section, Toggle } from "@/components/admin/admin-ui";

function SettingRow({ title, description, children }) { return <div className="flex flex-col gap-3 border-b border-gray-100 py-4 first:pt-0 last:border-0 last:pb-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium text-gray-800">{title}</p><p className="mt-0.5 max-w-xl text-xs text-gray-500">{description}</p></div><div className="shrink-0">{children}</div></div>; }
export default function SettingsPage() {
  const [settings,setSettings]=useState(adminSettings); const [saved,setSaved]=useState(false);
  const set=(key,value)=>{setSaved(false);setSettings((current)=>({...current,[key]:value}));};
  return <><PageHeader eyebrow="Configuration" title="Admin settings" description="Set platform defaults, upload rules, availability, and operational notifications." actions={<button type="button" onClick={()=>setSaved(true)} className="h-9 rounded-md bg-blue-600 px-4 text-xs font-semibold text-white">Save changes</button>} />
    {saved&&<div className="rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-medium text-emerald-700">Settings saved in this UI preview. Connect updateAdminSettings() to persist them.</div>}
    <div className="grid gap-4 xl:grid-cols-2"><Section title="Storage and uploads" description="Default limits applied to new accounts"><SettingRow title="Default storage quota" description="Assigned to every newly registered user."><div className="flex items-center gap-2"><input type="number" min="1" value={settings.defaultQuota} onChange={(e)=>set("defaultQuota",e.target.value)} className="h-9 w-24 rounded-md border border-gray-200 px-3 text-sm" /><span className="text-xs text-gray-500">GB</span></div></SettingRow><SettingRow title="Maximum upload size" description="Largest individual file accepted by upload requests."><div className="flex items-center gap-2"><input type="number" min="1" value={settings.maxUploadSize} onChange={(e)=>set("maxUploadSize",e.target.value)} className="h-9 w-24 rounded-md border border-gray-200 px-3 text-sm" /><span className="text-xs text-gray-500">GB</span></div></SettingRow><SettingRow title="Allowed file types" description="Comma-separated groups allowed by the client."><input value={settings.allowedTypes} onChange={(e)=>set("allowedTypes",e.target.value)} className="h-9 w-full rounded-md border border-gray-200 px-3 text-sm sm:w-72" /></SettingRow></Section>
      <Section title="Platform availability" description="Control access and maintenance communication"><SettingRow title="User registration" description="Allow new users to create Storix accounts."><Toggle label="User registration" checked={settings.registrationEnabled} onChange={(value)=>set("registrationEnabled",value)} /></SettingRow><SettingRow title="Maintenance mode" description="Show maintenance UI and pause normal user operations."><Toggle label="Maintenance mode" checked={settings.maintenanceMode} onChange={(value)=>set("maintenanceMode",value)} /></SettingRow></Section>
      <Section title="Admin notifications" description="Choose which operational events notify administrators"><SettingRow title="Email alerts" description="Receive a daily operational summary by email."><Toggle label="Email alerts" checked={settings.emailAlerts} onChange={(value)=>set("emailAlerts",value)} /></SettingRow><SettingRow title="Failed upload alerts" description="Notify administrators when upload failure rate increases."><Toggle label="Failed upload alerts" checked={settings.failedUploadAlerts} onChange={(value)=>set("failedUploadAlerts",value)} /></SettingRow></Section>
      <Section title="Storage warning thresholds" description="Usage levels that trigger user and admin notifications"><div className="grid grid-cols-3 gap-3">{settings.warningThresholds.map((threshold,index)=><label key={index} className="text-xs font-medium text-gray-600">Level {index+1}<div className="mt-1 flex items-center rounded-md border border-gray-200 bg-white"><input type="number" min="1" max="100" value={threshold} onChange={(e)=>set("warningThresholds",settings.warningThresholds.map((item,itemIndex)=>itemIndex===index?Number(e.target.value):item))} className="h-9 min-w-0 flex-1 bg-transparent px-3 text-sm outline-none" /><span className="pr-3 text-gray-400">%</span></div></label>)}</div><p className="mt-4 text-xs text-gray-500">Warnings are evaluated against each user&apos;s assigned quota.</p></Section></div>
  </>;
}
