"use client";

import { useCallback, useEffect, useState } from "react";
import { getAdminSettings, updateAdminSettings } from "@/lib/api/admin";
import { getAdminData } from "@/lib/admin/adminData";
import { ErrorState, LoadingState, PageHeader, Section, Toggle } from "@/components/admin/admin-ui";

const GB = 1024 ** 3;
function SettingRow({ title, description, children }) { return <div className="flex flex-col gap-3 border-b border-gray-100 py-4 first:pt-0 last:border-0 last:pb-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium text-gray-800">{title}</p><p className="mt-0.5 max-w-xl text-xs text-gray-500">{description}</p></div><div className="shrink-0">{children}</div></div>; }

export default function SettingsPage() {
  const [settings,setSettings]=useState(null); const [saved,setSaved]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const loadSettings=useCallback(async()=>{setLoading(true);setError("");try{const response=await getAdminSettings();const source=getAdminData(response).settings||{};setSettings({defaultQuota:Number((Number(source.defaultStorageLimit||0)/GB).toFixed(2)),maxUploadSize:Number((Number(source.maxFileUploadSize||0)/GB).toFixed(2)),allowedTypes:(source.allowedFileTypes||[]).join(", "),registrationEnabled:Boolean(source.allowRegistration),maintenanceMode:Boolean(source.maintenanceMode),warningThreshold:Number(source.storageWarningThreshold||80)});}catch(requestError){setError(requestError.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{const timer=setTimeout(loadSettings,0);return()=>clearTimeout(timer);},[loadSettings]);
  const set=(key,value)=>{setSaved(false);setSettings((current)=>({...current,[key]:value}));};
  const save=async()=>{setSaving(true);setError("");setSaved(false);try{await updateAdminSettings({defaultStorageLimit:Number(settings.defaultQuota)*GB,maxFileUploadSize:Number(settings.maxUploadSize)*GB,allowedFileTypes:settings.allowedTypes.split(",").map((value)=>value.trim()).filter(Boolean),storageWarningThreshold:Number(settings.warningThreshold),maintenanceMode:settings.maintenanceMode,allowRegistration:settings.registrationEnabled});setSaved(true);await loadSettings();}catch(requestError){setError(requestError.message);}finally{setSaving(false);}};

  if(loading&&!settings)return <><PageHeader eyebrow="Configuration" title="Admin settings" description="Loading live system settings." /><LoadingState /></>;
  if(!settings)return <><PageHeader eyebrow="Configuration" title="Admin settings" description="System settings are unavailable." /><ErrorState message={error} /></>;

  return <><PageHeader eyebrow="Configuration" title="Admin settings" description="Set platform defaults, upload rules, availability, and storage notifications." actions={<button type="button" disabled={saving} onClick={save} className="h-9 rounded-md bg-blue-600 px-4 text-xs font-semibold text-white disabled:opacity-50">{saving?"Saving...":"Save changes"}</button>} />
    {error&&<ErrorState message={error} />}{saved&&<div className="rounded-md border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-medium text-emerald-700">Settings saved successfully.</div>}
    <div className="grid gap-4 xl:grid-cols-2"><Section title="Storage and uploads" description="Default limits applied to new accounts"><SettingRow title="Default storage quota" description="Assigned to every newly registered user."><div className="flex items-center gap-2"><input type="number" min="0.01" step="0.01" value={settings.defaultQuota} onChange={(e)=>set("defaultQuota",e.target.value)} className="h-9 w-24 rounded-md border border-gray-200 px-3 text-sm" /><span className="text-xs text-gray-500">GB</span></div></SettingRow><SettingRow title="Maximum upload size" description="Largest individual file accepted by upload requests."><div className="flex items-center gap-2"><input type="number" min="0.01" step="0.01" value={settings.maxUploadSize} onChange={(e)=>set("maxUploadSize",e.target.value)} className="h-9 w-24 rounded-md border border-gray-200 px-3 text-sm" /><span className="text-xs text-gray-500">GB</span></div></SettingRow><SettingRow title="Allowed MIME types" description="Comma-separated MIME types accepted by the backend."><textarea value={settings.allowedTypes} onChange={(e)=>set("allowedTypes",e.target.value)} rows={3} className="w-full rounded-md border border-gray-200 px-3 py-2 text-sm sm:w-80" /></SettingRow></Section>
      <Section title="Platform availability" description="Control access and maintenance behavior"><SettingRow title="User registration" description="Allow new users to create Storix accounts."><Toggle label="User registration" checked={settings.registrationEnabled} onChange={(value)=>set("registrationEnabled",value)} /></SettingRow><SettingRow title="Maintenance mode" description="Enable the backend maintenance state for platform operations."><Toggle label="Maintenance mode" checked={settings.maintenanceMode} onChange={(value)=>set("maintenanceMode",value)} /></SettingRow><SettingRow title="Storage warning threshold" description="Usage percentage that triggers a storage warning."><div className="flex items-center rounded-md border border-gray-200 bg-white"><input type="number" min="1" max="100" value={settings.warningThreshold} onChange={(e)=>set("warningThreshold",e.target.value)} className="h-9 w-20 bg-transparent px-3 text-sm outline-none" /><span className="pr-3 text-xs text-gray-400">%</span></div></SettingRow></Section></div>
  </>;
}
