"use client";

import Link from "next/link";
import { useState } from "react";
import { activityLogs, adminFiles, adminUsers } from "@/lib/admin/adminMockData";
import { Badge, ConfirmModal, DataTable, formatBytes, PageHeader, RoleBadge, Section, StatCard, StorageProgressBar, UserStatusBadge } from "@/components/admin/admin-ui";

export default function UserDetailPage({ userId }) {
  const source = adminUsers.find((item) => item.id === userId) || adminUsers[0];
  const [user, setUser] = useState(source);
  const [quota, setQuota] = useState(Math.round(user.storageLimit / 1024 ** 3));
  const [modal, setModal] = useState(null);
  const files = adminFiles.filter((file) => file.ownerId === user.id).concat(adminFiles.slice(0,3)).slice(0,4);
  const fileColumns = [{key:"name",label:"File"},{key:"type",label:"Type"},{key:"size",label:"Size",render:(file)=>formatBytes(file.size)},{key:"folder",label:"Folder"},{key:"uploadedAt",label:"Uploaded"}];
  return <><div><Link href="/admin/users" className="text-xs font-semibold text-blue-600">Back to users</Link></div><PageHeader eyebrow="User details" title={user.name} description="Account profile, storage usage, recent content, and administrative controls." actions={<div className="flex gap-2"><UserStatusBadge status={user.status} /><RoleBadge role={user.role} /></div>} />
    <div className="grid gap-4 xl:grid-cols-[.7fr_1.3fr]"><Section title="Profile summary"><div className="flex items-center gap-4"><span className="flex h-16 w-16 items-center justify-center rounded-full bg-gray-900 text-lg font-semibold text-white">{user.avatar}</span><div><h2 className="text-lg font-semibold">{user.name}</h2><p className="text-sm text-gray-500">{user.email}</p><p className="mt-2 text-xs text-gray-400">Joined {user.createdAt} / Last active {user.lastActive}</p></div></div><dl className="mt-6 grid grid-cols-2 gap-4 border-t border-gray-100 pt-4"><div><dt className="text-xs text-gray-500">Account ID</dt><dd className="mt-1 text-sm font-medium">{user.id}</dd></div><div><dt className="text-xs text-gray-500">Authentication</dt><dd className="mt-1 text-sm font-medium">Google / session</dd></div></dl></Section><Section title="Storage summary" description={`${formatBytes(user.storageUsed)} of ${formatBytes(user.storageLimit)} used`}><div className="mt-2"><StorageProgressBar used={user.storageUsed} limit={user.storageLimit} /></div><div className="mt-6 grid grid-cols-3 gap-3"><div className="rounded-md bg-gray-50 p-3"><p className="text-xs text-gray-500">Used</p><p className="mt-1 font-semibold">{formatBytes(user.storageUsed)}</p></div><div className="rounded-md bg-gray-50 p-3"><p className="text-xs text-gray-500">Available</p><p className="mt-1 font-semibold">{formatBytes(user.storageLimit-user.storageUsed)}</p></div><div className="rounded-md bg-gray-50 p-3"><p className="text-xs text-gray-500">Limit</p><p className="mt-1 font-semibold">{formatBytes(user.storageLimit)}</p></div></div><div className="mt-5 flex flex-col gap-2 border-t border-gray-100 pt-4 sm:flex-row sm:items-end"><label className="flex-1 text-xs font-medium text-gray-600">Storage limit (GB)<input type="number" min="1" value={quota} onChange={(event) => setQuota(event.target.value)} className="mt-1 h-9 w-full rounded-md border border-gray-200 px-3 text-sm outline-none focus:border-blue-500" /></label><button type="button" onClick={() => setUser((item) => ({...item,storageLimit:Number(quota)*1024**3}))} className="h-9 rounded-md bg-blue-600 px-4 text-xs font-semibold text-white">Update quota</button></div></Section></div>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><StatCard label="Files" value={user.files} icon="files" /><StatCard label="Folders" value={user.folders} tone="amber" icon="files" /><StatCard label="Downloads" value="1,204" tone="green" icon="activity" /><StatCard label="Shared items" value="47" tone="violet" icon="users" /></div>
    <Section title="Recent files" action={<Link href="/admin/files" className="text-xs font-semibold text-blue-600">View all files</Link>}><DataTable columns={fileColumns} rows={files} /></Section>
    <div className="grid gap-4 xl:grid-cols-[1fr_.65fr]"><Section title="Activity timeline"><div className="space-y-4">{activityLogs.slice(0,5).map((item) => <div key={item.id} className="flex gap-3"><span className="mt-1.5 h-2 w-2 rounded-full bg-blue-500" /><div><p className="text-sm font-medium">{item.action}</p><p className="text-xs text-gray-500">{item.details}</p><p className="mt-1 text-[10px] text-gray-400">{item.date}</p></div></div>)}</div></Section><Section title="Admin actions" description="Changes here affect account access"><div className="space-y-2"><button type="button" onClick={() => setUser((item) => ({...item,role:item.role === "admin" ? "user" : "admin"}))} className="h-9 w-full rounded-md border border-gray-200 text-xs font-semibold text-gray-700">Change role to {user.role === "admin" ? "user" : "admin"}</button><button type="button" onClick={() => setModal("status")} className="h-9 w-full rounded-md border border-amber-200 text-xs font-semibold text-amber-700">{user.status === "active" ? "Block account" : "Unblock account"}</button><button type="button" onClick={() => setModal("delete")} className="h-9 w-full rounded-md border border-red-200 text-xs font-semibold text-red-600">Delete account</button></div></Section></div>
    <ConfirmModal open={Boolean(modal)} title={modal === "delete" ? "Delete this account?" : `${user.status === "active" ? "Block" : "Unblock"} ${user.name}?`} description={modal === "delete" ? "This frontend preview does not execute backend deletion. Connect the admin endpoint before enabling it." : "This updates the local UI preview. The API helper is ready for the backend endpoint."} confirmLabel={modal === "delete" ? "Delete user" : user.status === "active" ? "Block user" : "Unblock user"} tone={modal === "delete" ? "danger" : "warning"} onClose={() => setModal(null)} onConfirm={() => { if (modal === "status") setUser((item) => ({...item,status:item.status === "active" ? "blocked" : "active"})); setModal(null); }} />
  </>;
}
